apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: notes-app
spec:
  selector:
    app: notes-app   # Use the appropriate label to match your pod
  ports:
    - protocol: TCP
      port: 8000       # Port in the service
      targetPort: 8000 # Port in the pod
  type: ClusterIP #ClusterIp not exposes outside the cluster while NodePort Exposes port outside the cluster
